# Generated by Django 5.0 on 2025-10-13 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('country', models.CharField(max_length=20)),
                ('industry', models.CharField(max_length=30)),
                ('founded_year', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CompanyDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_type', models.CharField(max_length=100)),
                ('size', models.CharField(max_length=50)),
                ('ceo_name', models.CharField(max_length=30)),
                ('headquarters', models.CharField(max_length=50)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='api.company')),
            ],
        ),
        migrations.CreateModel(
            name='FinancialData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('revenue', models.DecimalField(decimal_places=2, max_digits=20)),
                ('net_income', models.DecimalField(decimal_places=2, max_digits=20)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_data', to='api.company')),
            ],
            options={
                'ordering': ['-year'],
                'unique_together': {('company', 'year')},
            },
        ),
    ]
